accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('<username>/', views.profile, name='profile'),
    path('<username>/fond_create', views.fond_create, name='fond_create'),
    path('<username>/fond_update', views.fond_update, name='fond_update'),
    path('<username>/fond_delete', views.fond_delete, name='fond_delete'),
    path('<int:user_pk>/follow/', views.follow, name='follow'),
]

# update 취향 설정, delete 추가 

movies/urls.py
from django.urls import path
from . import views

app_name = 'movies'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:movie_pk>/', views.detail, name='detail'),
    path('<int:movie_pk>/comments/create/', views.create_movie_comment, name='create_movie_comment'),
    path('<int:movie_pk>/comments/<int:moviecomment_pk>/delete/', views.delete_movie_comment, name='delete_movie_comment'),
    path('<int:movie_pk>/like/', views.like, name='like'),
]

pjt_final/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('community/', include('community.urls')),
    path('accounts/', include('accounts.urls')),
    path('movies/', include('movies.urls')),
    path('', include('movies.urls')),
]

movies/models.py
from django.db import models
from django.conf import settings

class Genre(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name

class Movie(models.Model):
    title = models.CharField(max_length=100)
    release_date = models.DateField()
    popularity = models.FloatField()
    vote_count = models.IntegerField()
    vote_average = models.FloatField()
    overview = models.TextField()
    poster_path = models.CharField(max_length=200)
    genres = models.ManyToManyField(Genre, related_name="movies")
    
    def __str__(self): # 포스터 링크 추가?
        return self.title

class MovieComment(models.Model):
    content = models.TextField()
    RANKS = [
        (1, '☆'),
        (2, '★'),
        (3, '★☆'),
        (4, '★★'),
        (5, '★★☆'),
        (6, '★★★'),
        (7, '★★★☆'),
        (8, '★★★★'),
        (9, '★★★★☆'),
        (10,'★★★★★'),
    ]
    rank = models.IntegerField(choices=RANKS, default=10)
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    movie_commment_created_at = models.DateTimeField(auto_now_add=True)
    movie_commment_updated_at = models.DateTimeField(auto_now=True)

movies/forms.py
from django import forms
from .models import MovieComment

class MovieCommentForm(forms.ModelForm):

    class Meta:
        model = MovieComment
        exclude = ['movie', 'user']

movies/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views.decorators.http import require_GET, require_POST, require_http_methods
from django.views.decorators.http import require_safe
from .models import Movie, Genre, MovieComment
from accounts.models import User
from django.contrib.auth import get_user_model
from django.core.paginator import Paginator
from django.core import serializers
from django.http import HttpResponse
from .forms import MovieCommentForm
from django.http.response import JsonResponse


# User의 취향에 맞게 영화 추천해주기
@require_safe
def index(request):
    
    movies = Movie.objects.all().order_by('-vote_average','-vote_count')
    person = User.objects.none()
    
    if request.user.is_authenticated:
        user_pk = request.user.id
        username = request.user.username
        person = get_object_or_404(get_user_model(), pk=user_pk)

    
    paginator = Paginator(movies, 10)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    rec_movies = Movie.objects.none()

    username = request.user.username
    if request.user.is_authenticated:
        person = get_object_or_404(get_user_model(), username=username)

        # QuerySet이 비어있는지 확인을 위한 초기화
        like_genres = 0
        hate_genres = 0
        like_movies = 0

        if person.like_genres.all():
            like_genres = person.like_genres.all()

        if person.hate_genres.all():
            hate_genres = person.hate_genres.all()
        
        if person.like_movies.all():
            like_movies = person.like_movies.all()

        


        # 취향 중 좋아하는 장르가 있다면, 해당 Genre QuerySet 생성
        if like_genres != 0:
            like_genres_QS = like_genres

            # 만약 싫어하는 장르가 겹치면 QuerySet에서 삭제
            if hate_genres != 0:
                for i in range(len(hate_genres)):
                    like_genres_QS = like_genres_QS.exclude(id=f'{hate_genres[i].id}')

        # 취향에서 선호하는 영화가 있다면, 해당 Movie 에 맞는 Genre QuerySet 생성
        if like_movies != 0:
            like_movies_genres_QS = Genre.objects.none() # 좋아하는 영화들의 장르들

            for i in range(len(like_movies)):
                like_movies_genres_QS_filtered = like_movies[i].genres.all()
                for k in range(len(like_movies[i].genres.all())):
                    if hate_genres != 0:
                        for j in range(len(hate_genres)):
                            if like_movies[i].genres.all()[k].id == hate_genres[j].id:
                                like_movies_genres_QS_filtered = like_movies_genres_QS_filtered.exclude(id=f'{hate_genres[j].id}')
                like_movies_genres_QS = like_movies_genres_QS.union(like_movies_genres_QS_filtered)

        # 취향 중 싫어 하는 장르가 있다면, 위 Genre QuerySet에서 삭제 

        # 둘 다 있다면, 위 QuerySet Union 후, 최종 Movie QuerySet 생성
        if like_genres!= 0 and like_movies != 0 :
            union_like_QS = like_genres_QS.union(like_movies_genres_QS) # 결합
            rec_movies = Movie.objects.none()
            for i in range(len(union_like_QS)):
                in_movies = (Movie.objects.filter(genres=f'{union_like_QS[i].id}'))
                if hate_genres != 0:
                    for j in range(len(hate_genres)): # in_movies 에서 싫어하는 장르 빼고 난 후 
                        in_movies = in_movies.exclude(genres=f'{hate_genres[j].id}')
                in_movies = in_movies.distinct()
                # like_movies 와 겹치는 영화 제거
                for j in range(len(like_movies)):
                    in_movies = in_movies.exclude(id=f'{like_movies[j].id}')

                rec_movies = rec_movies.union(in_movies)
                # rec_movies = rec_movies.order_by('vote_average').distinct()\

            # 만약 취향 중 싫어하는 장르가 좋아하는 장르와 영화를 모두 삭제시킨 경우, 
            if len(rec_movies) == 0:
                rec_movies = Movie.objects.all()
                if hate_genres != 0:
                    for i in range(len(hate_genres)):
                        rec_movies = rec_movies.exclude(genres=f'{hate_genres[i].id}')
        
        elif like_genres != 0:
            rec_movies = Movie.objects.none()
            for i in range(len(like_genres_QS)):
                in_movies = (Movie.objects.filter(genres=f'{like_genres_QS[i].id}'))
                in_movies = in_movies.distinct()
                rec_movies = rec_movies.union(in_movies)

        elif like_movies != 0:
            rec_movies = Movie.objects.none()
            for i in range(len(like_movies_genres_QS)):
                in_movies = (Movie.objects.filter(genres=f'{like_movies_genres_QS[i].id}'))
                if hate_genres != 0:
                    for j in range(len(hate_genres)): # in_movies 에서 싫어하는 장르 빼고 난 후 
                        in_movies = in_movies.exclude(genres=f'{hate_genres[j].id}')
                # 선호하는 영화 겹치는 항목 제거
                for j in range(len(like_movies)):
                    in_movies = in_movies.exclude(id=f'{like_movies[j].id}')
                rec_movies = rec_movies.union(in_movies)

        # 만약 취향 중 싫어하는 장르만 있다면, Movie 평점 순으로 불러온 후, 삭제
        else :
            rec_movies = Movie.objects.all()
            if hate_genres != 0:
                for i in range(len(hate_genres)):
                    rec_movies = rec_movies.exclude(genres=f'{hate_genres[i].id}')

        rec_movies = rec_movies.order_by('-vote_average','-vote_count') # 정렬
        rec_movies = rec_movies[:5] # 갯수 할당 

        print('rec_movies',rec_movies)
        print('hate_genres',hate_genres)

        # 추천 영화들 장르와 취향 추천 장르들 출력 후 비교
        for i in range(len(rec_movies)):
            print('recommend_movie', rec_movies[i].genres.all())
            # pass

        if like_genres!= 0 and like_movies != 0:
            print('union_like_QS',union_like_QS)
        
        elif like_genres != 0:
            print('like_genres_QS',like_genres_QS)
        
        elif like_movies != 0:
            print('like_movies_genres_QS',like_movies_genres_QS)

    # 만약 추천 영화가 아무것도 없다면, 
    if len(rec_movies) == 0:
        rec_movies = Movie.objects.all().order_by('-vote_average','-vote_count')
        rec_movies = rec_movies[:5] # 갯수 할당 
    
    # /movies/?page=2 ajax 요청 => json
    if request.headers.get('x-requested-with') == 'XMLHttpRequest':
        data = serializers.serialize('json', page_obj)
        return HttpResponse(data, content_type='application/json')
    # /movies/ 첫번째 페이지 요청 => html
    else:
        context = {
            'movies': page_obj,
            'rec_movies':rec_movies,
            'username':username,
            'person':person,
        }

        return render(request, 'movies/index.html', context)


@require_safe
def detail(request, movie_pk):

    STARS = [
        '',
        '☆',
        '★',
        '★☆',
        '★★',
        '★★☆',
        '★★★',
        '★★★☆',
        '★★★★',
        '★★★★☆',
        '★★★★★'
    ]

    person = User.objects.none()

    if request.user.is_authenticated:
        person = request.user

    this_movie = get_object_or_404(Movie, pk=movie_pk)
    movie_comments = this_movie.moviecomment_set.all()
    movie_comment_form = MovieCommentForm()
    rank_sum = 0
    rank_cnt = 0
    rank_avg = 0
    for comment in movie_comments:
        comment.star = STARS[comment.rank]
        rank_sum += int(comment.rank)
        rank_cnt += 1
    if rank_cnt >= 1:
        rank_avg = round(rank_sum / rank_cnt,2)

        this_movie.vote_average = rank_avg
        this_movie.save()


    no_more_comment = False

    my_comments = MovieComment.objects.filter(movie = this_movie)

    if request.user.is_authenticated:
        if len(my_comments) >= 1:
            for comment in my_comments:
                if comment.user_id == person.id:
                    no_more_comment = True
    
    context = {
        'movie': this_movie,
        'movie_comment_form': movie_comment_form,
        'movie_comments': movie_comments,
        'rank_avg' : rank_avg,
        'person' : person,
        'no_more_comment' : no_more_comment,
    }
    return render(request, 'movies/detail.html', context)

@require_POST
def create_movie_comment(request, movie_pk):
    movie = get_object_or_404(Movie, pk=movie_pk)
    movie_comment_form = MovieCommentForm(request.POST)
    if movie_comment_form.is_valid():
        movie_comment = movie_comment_form.save(commit=False)
        movie_comment.movie = movie
        movie_comment.user = request.user
        movie_comment.save()
        # movie_rank = movie.moviecomment_set.rank
        return redirect('movies:detail', movie.pk)
    context = {
        'movie_comment_form': movie_comment_form,
        'movie': movie,
        'movie_comments': movie.moviecomment_set.all(),
        'movie_rank': movie.moviecomment_set.rank,
    }
    return render(request, 'movies/detail.html', context)


@require_POST
def delete_movie_comment(request, movie_pk, moviecomment_pk):
    movie = get_object_or_404(Movie, pk=movie_pk)
    movie_comment = get_object_or_404(MovieComment, pk=moviecomment_pk)
    if request.user == movie_comment.user:
        movie_comment.delete()
    return redirect('movies:detail', movie.pk)


@require_POST
def like(request, movie_pk):
    if request.user.is_authenticated:
        movie = get_object_or_404(Movie, pk=movie_pk)
        person = request.user

        like_movies = person.like_movies.all()

        if like_movies.filter(pk=movie_pk).exists():
            person.like_movies.remove(movie) 
            isLiked = False
        else:
            person.like_movies.add(movie)
            person.save()

            isLiked = True
        context = {
            'isLiked': isLiked,
        }
        return JsonResponse(context)
    return redirect('accounts:login')

movies/templates/movies/detail.html
{% extends 'base.html' %}

{% block content %}
  <h2 class="text-center">{{ movie.title }}</h2>
  {% comment %} <h3>{{ movie.pk }} 번째 글</h3> {% endcomment %}
  <hr>
  <div class="img-center">
  <img src="{{ movie.poster_path}}"> <br>
  </div>
  {% comment %} <p>영화 제목: {{ movie.title }}</p> {% endcomment %}
  <br>
  <p>내용: {{ movie.overview }}</p>
  <p>개봉일: {{ movie.release_date }}</p>
  <p>인기도: {{ movie.popularity }}</p>
  <p>투표수: {{ movie.vote_count }}</p>
  
  {% if movie_comments|length %}
    <p>평점: {{ rank_avg }}</p>
  {% else %}
  <p>평점: {{ movie.vote_average }}</p>
  {% endif %}

  <div>장르:
    {% for genre in movie.genres.all %}
      {{genre.name}}
    {% endfor %}

  </div>

  <div class="detailpage">
      {% if request.user.is_authenticated %}
      <form id="like-form" data-movie-pk="{{ movie.pk }}" class="d-inline">
        {% csrf_token %}
        {% if movie in person.like_movies.all %}
          <button id="like-{{ movie.pk }}" class="btn btn-outline-dark">좋아요 취소</button>
        {% else %}
          <button id="like-{{ movie.pk }}" class="btn btn-outline-dark">좋아요</button>
        {% endif %}
      </form>

    
    {% else %}
      <button onclick = "location.href= '{% url 'accounts:login' %}'">좋아요</button>
      <hr>
    {% endif %} 
  </div>
  
 <hr>

  <h4>댓글 목록</h4>
  <ul>
  {% if movie_comments|length %}
    <p><b>{{ movie_comments|length }}개의 댓글이 있습니다.</b></p>
  {% endif %}
  {% for comment in movie_comments %}
  <li>
    <a href="{% url 'accounts:profile' comment.user.username %}" class="name_button">
      {{ comment.user }}
    </a>- {{ comment.content }} {{ comment.star }}

    {% if request.user == comment.user %}
    <form style="display: inline-block;" action="{% url 'movies:delete_movie_comment' movie.pk comment.pk %}" method="POST">
      {% csrf_token %}
      <button class="btn btn-outline-dark">[X]</button>
    </form>
    {% endif %}
  </li>

{% empty %}
  <li>아직 댓글이 없어요.</li>
{% endfor %}
</ul>

{% if request.user.is_authenticated %}
{% if no_more_comment %}
  <p> 평점 댓글 작성은 한개만 가능합니다.</p>
{% else %}
<form action="{% url 'movies:create_movie_comment' movie.pk %}" method="POST">
  {% csrf_token %}  
  {{ movie_comment_form }}
  <button class="btn btn-outline-dark">comment</button>
</form>
{% endif %}

{% else %}
<a href="{% url 'accounts:login' %}" class="btn btn-outline-dark">댓글을 작성하려면 로그인하세요.</a>
  <hr>
{% endif %} 
<hr>
<a href="{% url 'movies:index' %}" class="btn btn-outline-dark">back</a>
{% endblock  %}

{% block script %}
  <script>

    const form_lst = document.querySelectorAll('#like-form')

    form_lst.forEach(form => {
      const csrftoken = document.querySelector('[name=csrfmiddlewaretoken]').value;
      form.addEventListener('submit', function(event) {
        event.preventDefault()
        const moviePK = event.target.dataset.moviePk

        axios({
          method: 'post',
          url: `/movies/${moviePK}/like/`,
          headers: {'X-CSRFToken' : csrftoken}
        })

        .then(response => {
          const isLiked = response.data.isLiked

          const btn = document.querySelector(`#like-${moviePK}`)
          if (isLiked) {
            btn.innerText = '좋아요 취소'
          }
          else {
            btn.innerText = '좋아요'
          }
      

        })

      })

    })
  </script>
{% endblock script %}

movies/templates/movies/index.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
  <h1>Recent Movies</h1>

  <div id="carouselExampleCaptions" class="carousel slide" data-bs-ride="carousel">
    <div class="carousel-indicators">
      <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
      <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="1" aria-label="Slide 2"></button>
      <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="2" aria-label="Slide 3"></button>
    </div>
    <div class="carousel-inner">
      <div class="carousel-item active">
        <img src="{% static 'movies/c_1.jpg' %}" class="d-block w-100" alt="이터널스">
        <div class="carousel-caption d-none d-md-block">
          <h5>이터널스</h5>
          <p>#액션 #드라마 #판타지</p>
        </div>
      </div>
      <div class="carousel-item">
        <img src="{% static 'movies/c_2.jpg' %}" class="d-block w-100" alt="듄">
        <div class="carousel-caption d-none d-md-block">
          <h5>듄</h5>
          <p>#모험</p>
        </div>
      </div>
      <div class="carousel-item">
        <img src="{% static 'movies/c_3.jpg' %}" class="d-block w-100" alt="장르만로맨스">
        <div class="carousel-caption d-none d-md-block">
          <h5>장르만 로맨스</h5>
          <p>#드라마</p>
        </div>
      </div>
    </div>
    <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Next</span>
    </button>
  </div>

<div class = "card_genre">
  <h4>▸ 취향에 따른 영화 추천</h4>
  </div>

  <div class="main_lst1">
  {% for movie in rec_movies %}
    <div class="card">
      
        <!-- 각 카드 헤더 -->
        <div class="card-header">
          <div class="card-header-img">
          <img src="{{ movie.poster_path }}">
          </div>
        </div>
        <!--  카드 바디 헤더 -->
        <div class="card-body-header">
            
          <h4>{{ movie.title }}</h4>
          {% comment %} <p>개봉 - {{ movie.release_date }}</p> {% endcomment %}
          <p>
          장르 - 
            {% for genre in movie.genres.all %}
              {{genre.name}}
            {% endfor %}
            <br>
          평점 - {{ movie.vote_average }}
          <br>
          개봉 - {{ movie.release_date }}
          </p>
          <a href="{% url 'movies:detail' movie.pk %}" class="btn btn-outline-danger">자세히 보기<a>
      </div>
      
    </div>
    {% endfor %}
  </div>
  <div class="line_sum">
  {% if request.user.is_authenticated %}
    {% if username == request.user.username %}
      {% if person.like_genres.all or person.hate_genres.all or person.like_movies.all %}
        <ul> <a href="{% url 'accounts:fond_update' person.username %}" class="btn btn-outline-dark">취향 변경</a> </ul>
      {% else %}
        <ul> <a href="{% url 'accounts:fond_create' person.username %}" class="btn btn-outline-dark">취향 생성</a> </ul>
      {% endif %}
      <ul> <a href="{% url 'accounts:fond_delete' person.username %}" class="btn btn-outline-dark">취향 삭제</a> </ul>
    {% endif %}
  {% endif %}
  </div>
  <br>
  <br>
<div class="bottom_gap">
<h4>▸ 영화 목록</h4>
</div>
  <div>
    {% for movie in movies %}
      <div class="movie">
        <h3>{{ movie.title }}</h3>
        <p>{{ movie.overview }}</p>
        <a href="{% url 'movies:detail' movie.pk %}" class="btn btn-outline-dark">detail</a>
        <hr>
      </div>
    {% endfor %}
  </div>

{% endblock %}