accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('<username>/', views.profile, name='profile'),
    path('<username>/fond_create', views.fond_create, name='fond_create'),
    path('<username>/fond_update', views.fond_update, name='fond_update'),
    path('<username>/fond_delete', views.fond_delete, name='fond_delete'),
    path('<int:user_pk>/follow/', views.follow, name='follow'),
]

# update 취향 설정, delete 추가 

community/urls.py
from django.urls import path
from . import views

app_name = 'community'

urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('<int:review_pk>/', views.detail, name='detail'),
    path('<int:review_pk>/delete/', views.delete, name='delete'),
    path('<int:review_pk>/update/', views.update, name='update'),
    path('<int:review_pk>/comments/create/', views.create_comment, name='create_comment'),
    path('<int:review_pk>/comments/<int:comment_pk>/delete/', views.comments_delete, name='comments_delete'),
    path('<int:review_pk>/like/', views.like, name='like'),
]

movies/urls.py
from django.urls import path
from . import views

app_name = 'movies'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:movie_pk>/', views.detail, name='detail'),
    path('<int:movie_pk>/comments/create/', views.create_movie_comment, name='create_movie_comment'),
    path('<int:movie_pk>/comments/<int:moviecomment_pk>/delete/', views.delete_movie_comment, name='delete_movie_comment'),
    path('<int:movie_pk>/like/', views.like, name='like'),
]

pjt_final/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('community/', include('community.urls')),
    path('accounts/', include('accounts.urls')),
    path('movies/', include('movies.urls')),
    path('', include('movies.urls')),
]

community/models.py
from django.db import models
from django.conf import settings


class Review(models.Model):
    title = models.CharField(max_length=100)
    movie_title = models.CharField(max_length=50)
    RANKS = [
        (1, '☆'),
        (2, '★'),
        (3, '★☆'),
        (4, '★★'),
        (5, '★★☆'),
        (6, '★★★'),
        (7, '★★★☆'),
        (8, '★★★★'),
        (9, '★★★★☆'),
        (10,'★★★★★'),
    ]
    rank = models.IntegerField(choices=RANKS, default=10)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='like_reviews')
    
    



class Comment(models.Model):
    content = models.TextField()
    review = models.ForeignKey(Review, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    review_comment_created_at = models.DateTimeField(auto_now_add=True)
    review_comment_updated_at = models.DateTimeField(auto_now=True)

community/forms.py
from django import forms
from .models import Review, Comment


class ReviewForm(forms.ModelForm):
    
    class Meta:
        model = Review
        fields = ['title', 'movie_title', 'rank', 'content']


class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        exclude = ['review', 'user']

community/views.py
from django.http.response import JsonResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_GET, require_POST, require_http_methods
from django.contrib.auth.decorators import login_required
from .models import Review, Comment
from .forms import ReviewForm, CommentForm


@require_GET
def index(request):
    reviews = Review.objects.order_by('-pk')
    context = {
        'reviews': reviews,
    }
    return render(request, 'community/index.html', context)


@require_http_methods(['GET', 'POST'])
def create(request):
    if request.method == 'POST':
        form = ReviewForm(request.POST) 
        if form.is_valid():
            review = form.save(commit=False)
            review.user = request.user
            review.save()
            return redirect('community:detail', review.pk)
    else:
        form = ReviewForm()
    context = {
        'form': form,
    }
    return render(request, 'community/create.html', context)


@require_GET
def detail(request, review_pk):
    STARS = [
        '',
        '☆',
        '★',
        '★☆',
        '★★',
        '★★☆',
        '★★★',
        '★★★☆',
        '★★★★',
        '★★★★☆',
        '★★★★★'
    ]
    
    review = get_object_or_404(Review, pk=review_pk)
    review.star = STARS[review.rank]
    comments = review.comment_set.all()
    comment_form = CommentForm()
    context = {
        'review': review,
        'comment_form': comment_form,
        'comments': comments,

    }
    return render(request, 'community/detail.html', context)


@require_POST
def delete(request, review_pk):
    review = get_object_or_404(Review, pk=review_pk)
    if request.user.is_authenticated:
        if request.user == review.user: 
            review.delete()
            return redirect('community:index')
    return redirect('community:detail', review_pk)


@login_required
@require_http_methods(['GET', 'POST'])
def update(request, review_pk):
    review = get_object_or_404(Review, pk=review_pk)
    if request.user == review.user:
        if request.method == 'POST':
            form = ReviewForm(request.POST, instance=review)
            if form.is_valid():
                form.save()
                return redirect('community:detail', review.pk)
        else:
            form = ReviewForm(instance=review)
    else:
        return redirect('community:index')
    context = {
        'review': review,
        'form': form,
    }
    return render(request, 'community/update.html', context)



@require_POST
def create_comment(request, review_pk):
    review = get_object_or_404(Review, pk=review_pk)
    comment_form = CommentForm(request.POST)
    if comment_form.is_valid():
        comment = comment_form.save(commit=False)
        comment.review = review
        comment.user = request.user
        comment.save()
        return redirect('community:detail', review.pk)
    context = {
        'comment_form': comment_form,
        'review': review,
        'comments': review.comment_set.all(),
    }
    return render(request, 'community/detail.html', context)

@require_POST
def comments_delete(request, review_pk, comment_pk):
    if request.user.is_authenticated:
        comment = get_object_or_404(Comment, pk=comment_pk)
        if request.user == comment.user:
            comment.delete()
    return redirect('community:detail', review_pk)



@require_POST
def like(request, review_pk):
    if request.user.is_authenticated:
        review = get_object_or_404(Review, pk=review_pk)
        user = request.user

        if review.like_users.filter(pk=user.pk).exists():
            review.like_users.remove(user)
            isLiked = False
        else:
            review.like_users.add(user)
            isLiked = True
        context = {
            'isLiked': isLiked,
            'like_count': review.like_users.count()
        }
        return JsonResponse(context)
    return redirect('accounts:login')

community/templates/community/create.html
{% extends 'base.html' %}

{% block content %}
  <h1 class="text-center">CREATE</h1>
  <form action="" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" class="btn btn-outline-dark">
  </form>
  <hr>
  <a href="{% url 'community:index' %}" class="btn btn-outline-dark">back</a>
{% endblock %}

community/templates/community/detail.html
{% extends 'base.html' %}

{% block content %}
  <h2 class="text-center">DETAIL</h2>
  {% comment %} <h3>{{ review.pk }} 번째 글</h3> {% endcomment %}
  <hr>
  <p>제목: {{ review.title }}</p>
  <p>영화 제목: {{ review.movie_title }}</p>
  <p>내용: {{ review.content }}</p>
  <p> 평점: {{ review.star }} </p>

  {% comment %} <p>평점: {{ comment.star }}</p> {% endcomment %}
  <p>작성 시각: {{ review.created_at }}</p>
  <p>수정 시각: {{ review.updated_at }}</p>

  
  {% if user == review.user %}
    <div class="detailpage">
    <a href="{% url 'community:update' review.pk %}" class="btn btn-outline-dark">UPDATE</a>
    </div>
    <div class="detailpage">   
    <form action="{% url 'community:delete' review.pk %}" method="POST">
      {% csrf_token %}
      <input type="submit" value="DELETE" class="btn btn-outline-dark">
    </form>
     </div>
  {% endif %}
  <div class="detailpage">
      {% if request.user.is_authenticated %}
      <form id="like-form" data-review-pk="{{ review.pk }}" class="d-inline">
        {% csrf_token %}
        {% if user in review.like_users.all %}
          <button id="like-{{ review.pk }}" class="btn btn-outline-dark">좋아요 취소</button>
        {% else %}
          <button id="like-{{ review.pk }}" class="btn btn-outline-dark">좋아요</button>
        {% endif %}
      </form>
      <p  id="like-box-{{ review.pk }}"> {{ review.like_users.all|length }}명이 이 글을 좋아합니다.</p>
    
    {% else %}
      <p  id="like-box-{{ review.pk }}"> {{ review.like_users.all|length }}명이 이 글을 좋아합니다.</p>
      {% comment %}  배포시 수정 필요 {% endcomment %}
      <button onclick = "location.href= '{% url 'accounts:login' %}'" class="btn btn-outline-dark"> 좋아요 </button>
      <hr>
    {% endif %} 
  </div>
  <hr>

  <h4>댓글 목록</h4>
  {% if comments|length %}
    <p><b>{{ comments|length }}개의 댓글이 있습니다.</b></p>
  {% endif %}
  {% for comment in comments %}
    <div>
       <a href="{% url 'accounts:profile' comment.user.username %}" class="name_button">
      {{ comment.user }}
    </a>- {{ comment.content }}
      {% if user == comment.user %}
          <form action="{% url 'community:comments_delete' review.pk comment.pk %}" method="POST" class="d-inline">
            {% csrf_token %}
            <input type="submit" value="DELETE" class="btn btn-outline-dark">
          </form>
        {% endif %}
    </div>
  {% empty %}
    <p><b>댓글이 없어요..</b></p>
  {% endfor %}
  <hr>
  {% if request.user.is_authenticated %}
    <form action="{% url 'community:create_comment' review.pk %}" method="POST">
      {% csrf_token %}
      {{ comment_form }}
      <input type="submit" class="btn btn-outline-dark">
    </form>
  {% else %}
    <a href="{% url 'accounts:login' %}" class="btn btn-outline-dark">댓글을 작성하려면 로그인하세요.</a>
  {% endif %}
  <hr>
  <a href="{% url 'community:index' %}" class="btn btn-outline-dark">back</a>


{% endblock  %}

{% block script %}
  <script>

    const form_lst = document.querySelectorAll('#like-form')

    form_lst.forEach(form => {
      const csrftoken = document.querySelector('[name=csrfmiddlewaretoken]').value;
      form.addEventListener('submit', function(event) {
        event.preventDefault()
        const reviewPk = event.target.dataset.reviewPk

        axios({
          method: 'post',
          url: `/community/${reviewPk}/like/`,
          headers: {'X-CSRFToken' : csrftoken}
        })

        .then(response => {
          const isLiked = response.data.isLiked
          const like_count = response.data.like_count

          const btn = document.querySelector(`#like-${reviewPk}`)
          if (isLiked) {
            btn.innerText = '좋아요 취소'
          }
          else {
            btn.innerText = '좋아요'
          }

          const likeBox = document.querySelector(`#like-box-${reviewPk}`)

          likeBox.innerText = `${like_count}명이 이 글을 좋아합니다.`

        })

      })

    })
  </script>
{% endblock script %}

community/templates/community/index.html
{% extends 'base.html' %}

{% block content %}
  <h1>Community</h1>
  <hr>
  {% if  reviews %}
    {% for review in reviews %}
      <p>작성자 : <a href="{% url 'accounts:profile' review.user.username %}"  class="name_button">{{ review.user }}</a></p>
      {% comment %} <p>글 번호: {{ review.pk }}</p> {% endcomment %}
      <p>글 제목: {{ review.title }}</p>
      <p>글 내용: {{ review.content }}</p>
      
      {% if request.user.is_authenticated %}

      <form id="like-form" data-review-pk="{{ review.pk }}" class="d-inline">
        {% csrf_token %}
        {% if user in review.like_users.all %}
          <button id="like-{{ review.pk }}" class="btn btn-outline-dark">좋아요 취소</button>
        {% else %}
          <button id="like-{{ review.pk }}" class="btn btn-outline-dark">좋아요</button>
        {% endif %}
      </form>
      <p  id="like-box-{{ review.pk }}"> {{ review.like_users.all|length }}명이 이 글을 좋아합니다.</p>
    
    {% else %}
      <p  id="like-box-{{ review.pk }}"> {{ review.like_users.all|length }}명이 이 글을 좋아합니다.</p>
      {% comment %}  배포시 수정 필요 {% endcomment %}
      <button type="button" onclick="location.href='{% url 'accounts:login' %}'" class="btn btn-outline-dark">좋아요</button>
      <hr>
    {% endif %}

      {% if request.user.is_authenticated %}
        <a href="{% url 'community:detail' review.pk %}" class="btn btn-outline-dark">DETAIL</a>
        <hr>
      {% else %}
        <a href="{% url 'accounts:login' %}" class="btn btn-outline-dark">DETAIL</a>
        <hr>
      {% endif %}
      
    {% endfor %}
  
  {% else %}
  <p> 게시글이 없습니다. </p>
{% endif %}

{% endblock %}

{% block script %}
  <script>

    const form_lst = document.querySelectorAll('#like-form')

    form_lst.forEach(form => {
      const csrftoken = document.querySelector('[name=csrfmiddlewaretoken]').value;
      form.addEventListener('submit', function(event) {
        event.preventDefault()
        const reviewPk = event.target.dataset.reviewPk

        axios({
          method: 'post',
          url: `/community/${reviewPk}/like/`,
          headers: {'X-CSRFToken' : csrftoken}
        })

        .then(response => {
          const isLiked = response.data.isLiked
          const like_count = response.data.like_count

          const btn = document.querySelector(`#like-${reviewPk}`)
          if (isLiked) {
            btn.innerText = '좋아요 취소'
          }
          else {
            btn.innerText = '좋아요'
          }

          const likeBox = document.querySelector(`#like-box-${reviewPk}`)

          likeBox.innerText = `${like_count}명이 이 글을 좋아합니다.`

        })

      })

    })
  </script>
{% endblock script %}

community/templates/community/update.html
{% extends 'base.html' %}

{% block content %}
  <h1>UPDATE</h1>
  <form action="{% url 'community:update' review.pk %}" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="수정" class="btn btn-outline-dark">
  </form>
  <hr>
  <a href="{% url 'community:index' %}" class="btn btn-outline-dark">back</a>
{% endblock content %}