accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('<username>/', views.profile, name='profile'),
    path('<username>/fond_create', views.fond_create, name='fond_create'),
    path('<username>/fond_update', views.fond_update, name='fond_update'),
    path('<username>/fond_delete', views.fond_delete, name='fond_delete'),
    path('<int:user_pk>/follow/', views.follow, name='follow'),
]

# update 취향 설정, delete 추가 

movies/urls.py
from django.urls import path
from . import views

app_name = 'movies'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:movie_pk>/', views.detail, name='detail'),
    path('<int:movie_pk>/comments/create/', views.create_movie_comment, name='create_movie_comment'),
    path('<int:movie_pk>/comments/<int:moviecomment_pk>/delete/', views.delete_movie_comment, name='delete_movie_comment'),
    path('<int:movie_pk>/like/', views.like, name='like'),
]

pjt_final/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('community/', include('community.urls')),
    path('accounts/', include('accounts.urls')),
    path('movies/', include('movies.urls')),
    path('', include('movies.urls')),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from movies.models import Genre, Movie

class User(AbstractUser):
    followings = models.ManyToManyField('self', symmetrical=False, related_name='followers')
    like_genres = models.ManyToManyField(Genre, null =True, blank = True, related_name="like_genres")
    hate_genres = models.ManyToManyField(Genre, null =True, blank = True, related_name="hate_genres")
    like_movies = models.ManyToManyField(Movie, null =True, blank = True, related_name="like_movies")

# 유저의 취향 좋아하는 장르 , 싫어하는 장르, 선호하는 영화
# 장르는 char로 받은 다음에 integer로 매칭 -> 
# movies.genre id <-> name 으로 매칭
# movies_movie_genres 으로 m:n movie_id, genre_id 로 매칭

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model
from .models import User
from django import forms


class CustomUserCreationForm(UserCreationForm):

    class Meta(UserCreationForm.Meta):
        model = get_user_model()
        fields = UserCreationForm.Meta.fields

class FondForm(forms.ModelForm):

    class Meta:
        model = User
        fields = ['like_genres', 'hate_genres', 'like_movies']

accounts/views.py
from django.http.response import JsonResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_POST, require_http_methods
from .forms import CustomUserCreationForm
from .forms import FondForm
from community.models import Review
from movies.models import MovieComment



@require_http_methods(['GET', 'POST'])
def signup(request):
    if request.user.is_authenticated:
        return redirect('community:index')

    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            auth_login(request, user)
            return redirect('community:index')
    else:
        form = CustomUserCreationForm()
    context = {
        'form': form,
    }
    return render(request, 'accounts/signup.html', context)


@require_http_methods(['GET', 'POST'])
def login(request):
    if request.user.is_authenticated:
        return redirect('community:index')

    if request.method == 'POST':
        form = AuthenticationForm(request, request.POST)
        if form.is_valid():
            auth_login(request, form.get_user())
            return redirect(request.GET.get('next') or 'community:index')
    else:
        form = AuthenticationForm()
    context = {
        'form': form,
    }
    return render(request, 'accounts/login.html', context)


@require_POST
def logout(request):
    auth_logout(request)
    return redirect('community:index')

# profile 영화 포스터 정보 전달

# 추가로 쓴 댓글, 쓴 
@login_required
def profile(request, username):

    STARS = [
        '',
        '☆',
        '★',
        '★☆',
        '★★',
        '★★☆',
        '★★★',
        '★★★☆',
        '★★★★',
        '★★★★☆',
        '★★★★★'
    ]

    person = get_object_or_404(get_user_model(), username = username)
    comments = MovieComment.objects.filter(user_id = person.id)
    
    if len(comments):
        for i in range (len(comments)) :
            comments[i].star = STARS[comments[i].rank]

    reviews = Review.objects.filter(user_id = person.id)
    context = {
        'person': person,
        'username':username,
        'comments':comments,
        'reviews':reviews,
        'STARS':STARS,
    }
    return render(request, 'accounts/profile.html', context)


@require_POST
def follow(request, user_pk):
    if request.user.is_authenticated:
        person = get_object_or_404(get_user_model(), pk=user_pk)
        user = request.user
        if person != user:
            if person.followers.filter(pk=user.pk).exists():
                person.followers.remove(user)
                isFollowed = False
            else:
                person.followers.add(user)
                isFollowed = True
            context = {
                'isFollowed':isFollowed,
                'following_count': person.followings.count(),
                'followers_count': person.followers.count()
            }
            return JsonResponse(context)
        return redirect('accounts:profile', person.username)
    return render(request, 'accounts/login.html')


# create 취향
# 좋아하는 장르, 싫어하는 장르, 좋아하는 영화 선택
@require_http_methods(['GET', 'POST'])
def fond_create(request, username):
    if request.user.is_authenticated:
        person = get_object_or_404(get_user_model(), username=username)
        if request.method == 'POST':
            form = FondForm(request.POST)
             
            if form.is_valid():
                myquery = dict(request.POST)

                if 'like_genres' in myquery:
                    for i in range(len(myquery['like_genres'])):
                        person.like_genres.add(myquery['like_genres'][i])

                if 'hate_genres' in myquery:
                    for i in range(len(myquery['hate_genres'])):
                        person.hate_genres.add(myquery['hate_genres'][i])

                if 'like_movies' in myquery:
                    for i in range(len(myquery['like_movies'])):
                        person.like_movies.add(myquery['like_movies'][i])

                person.save()
        
                return redirect('accounts:profile', username)
        else:
            form = FondForm()
        context = {
            'form': form,
            'username': username,
            'person':person,
        }
        return render(request, 'accounts/fond_create.html', context)
    return redirect('accounts:profile', username)


# update 취향

@require_http_methods(['GET', 'POST'])
def fond_update(request, username):
    if request.user.is_authenticated:
        person = get_object_or_404(get_user_model(), username=username)
        if request.method == 'POST':
            form = FondForm(request.POST, instance=person) 
            if form.is_valid():
                person.like_genres.clear()
                person.hate_genres.clear()
                person.like_movies.clear()

                myquery = dict(request.POST)

                if 'like_genres' in myquery:
                    for i in range(len(myquery['like_genres'])):
                        person.like_genres.add(myquery['like_genres'][i])

                if 'hate_genres' in myquery:
                    for i in range(len(myquery['hate_genres'])):
                        person.hate_genres.add(myquery['hate_genres'][i])

                if 'like_movies' in myquery:
                    for i in range(len(myquery['like_movies'])):
                        person.like_movies.add(myquery['like_movies'][i])

                person.save()

                return redirect('accounts:profile', username)
        else:
            form = FondForm(instance=person)
        context = {
            'form': form,
            'username': username,
            'person':person,
        }
        return render(request, 'accounts/fond_update.html', context)
    return redirect('accounts:profile', username)

# delete 취향
@require_http_methods(['GET', 'POST'])
def fond_delete(request, username):
    if request.user.is_authenticated:
        person = get_object_or_404(get_user_model(), username=username)
        if person == request.user:
            person.like_genres.clear()
            person.hate_genres.clear()
            person.like_movies.clear()
        return redirect('accounts:profile', username)
    return redirect('accounts:profile', username)

accounts/templates/accounts/fond_create.html
{% extends 'base.html' %}

{% block content %}
<h1>취향 생성</h1>
{% comment %} <form action="" method="POST">
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit">
</form> {% endcomment %}

{% if request.user.is_authenticated %}
    <form action="{% url 'accounts:fond_create' username %}" method="POST">
      {% csrf_token %}
      {{ form }}
      <input type="submit">
    </form>
  {% else %}
    <a href="{% url 'accounts:login' %}">취향을 생성하려면 로그인하세요.</a>
  {% endif %}
  <a href="{% url 'accounts:profile' person.username %}" class="btn btn-outline-dark">back</a>

{% endblock  %}

accounts/templates/accounts/fond_update.html
{% extends 'base.html' %}

{% block content %}
<h1>취향 변경</h1>
{% comment %} <form action="" method="POST">
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit">
</form> {% endcomment %}

{% if request.user.is_authenticated %}
    <form action="{% url 'accounts:fond_update' username %}" method="POST">
      {% csrf_token %}
      {{ form }}
      <input type="submit">
    </form>
  {% else %}
    <a href="{% url 'accounts:login' %}">취향을 생성하려면 로그인하세요.</a>
  {% endif %}
  <a href="{% url 'accounts:profile' person.username %}" class="btn btn-outline-dark">back</a>

{% endblock  %}

accounts/templates/accounts/login.html
{% extends 'base.html' %}

{% block content %}
<h1>로그인</h1>
<form action="" method="POST">
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit" class="btn btn-outline-dark">
</form>
{% endblock  %}

accounts/templates/accounts/profile.html
{% extends 'base.html' %}

{% block content %}
  <h1>{{ person.username }}의 프로필 페이지</h1>
  {% with followings=person.followings.all followers=person.followers.all %}
    <div>
      <div id="follow-count" class="profile_total">
        팔로잉 : {{ followings|length }} / 팔로워 : {{ followers|length }}
      </class=>
      {% if request.user != person %}
        <div>
          <form id="follow-form" data-user-id="{{ person.pk }}">
            {% csrf_token %}
            {% if request.user in followers %}
              <button>언팔로우</button>
            {% else %}
              <button>팔로우</button>
            {% endif %}
          </form>
        </div>
      {% endif %}
    </div>
    <div class="MyFavMov">

      <div class="line_sum">
      <ul><h3> My FavMov </h3></ul>
      {% if request.user.is_authenticated %}
        {% if username == request.user.username %}
          {% if person.like_genres.all or person.hate_genres.all or person.like_movies.all %}
            <ul> <a href="{% url 'accounts:fond_update' person.username %}" class="btn btn-outline-dark">취향 변경</a> </ul>
          {% else %}
            <ul> <a href="{% url 'accounts:fond_create' person.username %}" class="btn btn-outline-dark">취향 생성</a> </ul>
          {% endif %}
        <ul> <a href="{% url 'accounts:fond_delete' person.username %}" class="btn btn-outline-dark">취향 삭제</a> </ul>
      {% endif %}
    {% endif %}
  </div>
    </div>

  <br>
  <br>
  <br>
    <div class="profile_total">
       {% comment %} 썼던 평점 댓글, 게시글 출력 {% endcomment %}
      <p> 작성한 게시글 </p>
      {% if reviews|length %} |
      {% for review in reviews  %}
      {{ review.title }} |
      {% endfor %}
      {% else %}
        <p> 작성한 게시글이 없습니다. </p>
      {% endif %}
      <br>
      <br>
      <p> 작성한 댓글 </p>
      {% if comments|length %} |
      {% for comment in comments  %}
      {{ comment.movie.title }} : {{ comment.content }} - {{ comment.star }} |
      {% endfor %}
        {% else %}
        <p> 작성한 댓글이 없습니다. </p>
      {% endif %}
      <br>
      <br>

      <div> 선호하는 장르 :
        {% if person.like_genres.all %}
          {% for genre in person.like_genres.all %}
            < {{ genre }} >
          {% endfor%}
        {% else %}
          <p>선호하는 장르가 없습니다.</p>
        {% endif %}
      </div>
    </div>

    <div class="profile_total">
     <div> 비선호하는 장르 :
        {% if person.hate_genres.all %}
          {% for genre in person.hate_genres.all %}
          < {{ genre }} >
          {% endfor%}
        {% else %}
          <p>비선호하는 장르가 없습니다.</p>
        {% endif %}
      </div>
    </div>

 
   
 
      <div class="profile_total"> 좋아하는 영화 :
        
          {% if person.like_movies.all %}
            {% for movie in person.like_movies.all %}
            <div>
            <div class="profile_fav"> 
              <div class="card2" style="width: 18rem;">
              <img src="{{ movie.poster_path }}" class="card-img-top" alt="poster_{{ movie.poster_path }}">
              <div class="card-body">
                <h4>{{ movie.title }}</h4>
                <a href="{% url 'movies:detail' movie.pk %}" class="btn btn-outline-dark">Detail</a>
              </div>
            </div>
          
              
            </div>
            </div>
            {% endfor%}
          {% else %}
            <p>좋아하는 영화가 없습니다.</p>
          {% endif %}
      </div>
   
    {% comment %} 이미지 태그 활용 {% endcomment %}

  

 

  {% endwith %}
{% endblock %}

{% block script %}
<script>
  const form = document.querySelector('#follow-form')
  const csrftoken = document.querySelector('[name=csrfmiddlewaretoken]').value;

  form.addEventListener('submit', function(evnet) {
    event.preventDefault()
    const userId = event.target.dataset.userId

    axios({
      method: 'post',
      url: `/accounts/${userId}/follow/`,
      headers: {'X-CSRFToken' : csrftoken}
    })
    .then(response => {
      const isFollowed = response.data.isFollowed
      const followers_count = response.data.followers_count
      const followings_count = response.data.following_count

      const btn = document.querySelector('#follow-form > button')
      btn.classList.toggle('btn-primary')
      btn.classList.toggle('btn-secondary')
      if (isFollowed) {
        btn.innerText = '언팔로우'
      }
      else {
        btn.innerText = '팔로우'
      }

      const followBox = document.querySelector('#follow-count')

      followBox.innerText = `팔로잉 : ${followings_count} / 팔로워 : ${followers_count}`
    })
    
  })

</script>


{% endblock script %}

accounts/templates/accounts/signup.html
{% extends 'base.html' %}

{% block content %}
<h1>회원가입</h1>
<form action="" method="POST">
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit" class="btn btn-outline-dark">
</form>
{% endblock  %}