accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('<username>/', views.profile, name='profile'),
    path('<username>/fond_create', views.fond_create, name='fond_create'),
    path('<username>/fond_update', views.fond_update, name='fond_update'),
    path('<username>/fond_delete', views.fond_delete, name='fond_delete'),
    path('<int:user_pk>/follow/', views.follow, name='follow'),
]

# update 취향 설정, delete 추가 

community/urls.py
from django.urls import path
from . import views

app_name = 'community'

urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('<int:review_pk>/', views.detail, name='detail'),
    path('<int:review_pk>/delete/', views.delete, name='delete'),
    path('<int:review_pk>/update/', views.update, name='update'),
    path('<int:review_pk>/comments/create/', views.create_comment, name='create_comment'),
    path('<int:review_pk>/comments/<int:comment_pk>/delete/', views.comments_delete, name='comments_delete'),
    path('<int:review_pk>/like/', views.like, name='like'),
]

movies/urls.py
from django.urls import path
from . import views

app_name = 'movies'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:movie_pk>/', views.detail, name='detail'),
    path('<int:movie_pk>/comments/create/', views.create_movie_comment, name='create_movie_comment'),
    path('<int:movie_pk>/comments/<int:moviecomment_pk>/delete/', views.delete_movie_comment, name='delete_movie_comment'),
    path('<int:movie_pk>/like/', views.like, name='like'),
]

pjt_final/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('community/', include('community.urls')),
    path('accounts/', include('accounts.urls')),
    path('movies/', include('movies.urls')),
    path('', include('movies.urls')),
]

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
  <title>Document</title>
  <link rel="preconnect" href="https://fonts.googleapis.com">   
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Gowun+Batang&display=swap" rel="stylesheet">

  <style>

    body{

        font-family: 'Gowun Batang', serif;
        background-color: rgb(248, 248, 255);
        margin-top:100px;
        
    }
   
    .movie-list{margin-top:100px;}
    h1{
        margin-bottom:30px;

    }

    #input1 {
        background-color: transparent;
        color: rgb(192, 192, 192);
        border-width:0px;
    }

    .main_lst1 {
        width:100%;
        height:400px;
        display: flex;
        justify-content:center;
    }
    .card_genre {
        margin-top: 40px;
        margin-left: 30px;
    }
    .cards {
        background: #f6f0fa;
        padding: 10px;
        margin: 0 auto;
        overflow: hidden;
   
            }

    .card {
        height: 300px;
        width: 18rem;
        border-radius: 15px;
        display: inline;
        margin-top: 30px;
        margin-left: 30px;
        margin-bottom: 30px;
        box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
        overflow: hidden;
        float: left;
        
        }


    .card:hover .card-header  {
        opacity: 0.1;
        height: 20px;
    }
    .card-header{
        width: 100%;
        height: 200px;
    }
    .card-header-img {
        line-height: 30px;
        display: flex;
        justify-content: center;
        align-items: center;
        overflow: hidden;
        
    }
    .card-header-img img{
        max-width:60%;
        max-height:60%;
        display:block;
     
    }

    .card-body-header{
        margin: 20px 20px 0px 20px;
       
    }
    .card-body-header h4{
        padding:10px 0px 0px 0px;
        display: inline-block;
        width:150px;
        white-space:nowrap;
        overflow:hidden;
        text-overflow: ellipsis;

        white-space:normal;
        line-height:1;
        
    }


    .card-body-hashtag {
        color: rgb(0,0,0);
        padding:20px 0px 20px 0px;
    }

 

    .btn btn-outline-danger{
        margin: 0 auto;
       
    }

    .MyFavMov {
        padding:30px 0px 0px 0px;
    }
    .card-body > h4{
    display: inline-block;
    width: 200px; 
    white-space: nowrap; 
    overflow: hidden; 
    text-overflow: ellipsis;

    }
    .detailpage {
        padding:10px 0px 10px 0px;
    }
    .detailpage > button{
        padding:10px 0px 10px 0px;
    }
    .detailpage > p{
    padding:10px 0px 10px 0px;
    }

    .name_button {
     text-decoration:none;
     font-size:1.2em;   
     color:rgb(0,0,0);
     text-align: center;
    }
    .name_button:hover{
  
     color:white;
     background-color:grey;
     border-top-left-radius:5px;
     border-top-right-radius:5px;
     border-bottom-right-radius:5px;
     border-bottom-left-radius:5px;

    }
    .fav_genres{
    margin:100px 0px 0px 0px;
    }

    .profile_fav img{
        margin:10px 0px 0px 0px;
        width:auto;
        height:350px;
    }

    .profile_fav {
        display: inline;
        float:left;
        display: flex;
        justify-content: space-between;
        margin: 0 10px;
        margin-top: 65px;
        flex-wrap: wrap;
    }
 
    .line_sum > ul{
    float:left;
    margin:10px 0px 0px 0px;
    }
    .profile_total{
    margin:10px 0px 0px 20px;   
    }
    .img-center{
        text-align: center;
    }
    .bottom_gap{
      margin: 60px 0px 30px 0px;    
    }

  </style>
</head>
<body>
  <div>
  
  </div>
  <div class="container">
    <div>
    <nav class="navbar fixed-top navbar-expand-lg navbar-dark bg-dark px-5">
    <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'movies:index' %}">FavMov</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
        <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link" aria-current="page" href="{% url 'community:index'%}">Community</a>
        </li>

        {% if user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'community:create'%}">New Review</a>
        {% else %} 
          <a class="nav-link" href="{% url 'accounts:login'%}">New Review</a>
        {% endif %} 
        </li>
        
        {% if user.is_authenticated %}
        <li class="nav-item">
        <a class="nav-link" href={% url 'accounts:profile' user %}>내 프로필 </a>
        </li>
        <form class="nav-link" action="{% url 'accounts:logout' %}" method="POST">
        {% csrf_token %}
        <input id="input1" type="submit" value="Logout">
        </form> 
                      
        {% else %}
            <li class="nav-item">
            <a class="nav-link" href="{% url 'accounts:signup' %}">Sign up</a>
            </li>
            <li class="nav-item">
            <a class="nav-link" href="{% url 'accounts:login' %}">Login</a>
            </li>
        {% endif %}
        </ul>
    </div>
    </div>
    </nav>
  </div>
  

    {% block content %}
    {% endblock %}
  </div>


  <script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js" integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf" crossorigin="anonymous"></script>
  {% block script%}
  {% endblock %}

</body>


</html>